name: Update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16.x'

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os}}-node-
      
      - run: npm install

      - run: >
          STRAVA_API_CLIENT_ID=${{ secrets.STRAVA_API_CLIENT_ID }}
          STRAVA_API_CLIENT_ID=${{ secrets.STRAVA_API_CLIENT_ID }}
          STRAVA_API_CLIENT_SECRET=${{ secrets.STRAVA_API_CLIENT_SECRET }}
          STRAVA_API_REFRESH_TOKEN=${{ secrets.STRAVA_API_REFRESH_TOKEN }}
          STRAVA_OAUTH_BASE_URL=${{ secrets.STRAVA_OAUTH_BASE_URL }}
          STRAVA_API_BASE_URL=${{ secrets.STRAVA_API_BASE_URL }}
          THUNDERFOREST_API_KEY=${{ secrets.THUNDERFOREST_API_KEY }}
          node index.js
        
      - run: git config user.name 'oktupol'
      - run: git config user.email 'automatic-git-commits@nwie.land'
      - run: git add README.md
      - run: git add assets
      - run: git diff --quiet README.md || git commit -m '[gh-action] Update README'
      - run: git push origin master